### ISSUE TITLE
main/libedit failed to package on stage0 (bootstrap)

### ISSUE THREAD

**Issue by yopito** [chimera-linux/cports#104]
using rev b03ec5e2:
```
...
=> libedit-20220411-r0: running post_install...
=> libedit-readline-devel-20220411-r0: running pkg_install...
=> libedit-readline-devel-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-20220411/usr/include/readline -> /cports/bldroot-stage0/destdir/libedit-readline-devel-20220411
=> libedit-readline-devel-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-20220411/usr/lib/libhistory.a -> /cports/bldroot-stage0/destdir/libedit-readline-devel-20220411
=> libedit-readline-devel-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-20220411/usr/lib/libhistory.so -> /cports/bldroot-stage0/destdir/libedit-readline-devel-20220411
=> libedit-readline-devel-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-20220411/usr/lib/libreadline.a -> /cports/bldroot-stage0/destdir/libedit-readline-devel-20220411
=> libedit-readline-devel-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-20220411/usr/lib/libreadline.so -> /cports/bldroot-stage0/destdir/libedit-readline-devel-20220411
=> libedit-readline-devel-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-20220411/usr/lib/pkgconfig/readline.pc -> /cports/bldroot-stage0/destdir/libedit-readline-devel-20220411
=> libedit-readline-devel-20220411-r0: running post_install hook: 000_handle_modes...
=> libedit-readline-devel-20220411-r0: running post_install hook: 001_hardlinks...
=> libedit-readline-devel-20220411-r0: detecting hardlinks
=> libedit-readline-devel-20220411-r0: running post_install hook: 002_uncompress_manpages...
=> libedit-readline-devel-20220411-r0: running post_install hook: 003_remove_misc...
=> libedit-readline-devel-20220411-r0: running post_install hook: 004_remove_libtool_archives...
=> libedit-readline-devel-20220411-r0: running post_install hook: 005_remove_perl_files...
=> libedit-readline-devel-20220411-r0: running post_install hook: 007_strip_debug...
=> libedit-readline-devel-20220411-r0: running post_install hook: 008_rename_python_bindings...
=> libedit-readline-devel-20220411-r0: running post_install hook: 009_remove_pkgconf_sysroot...
=> libedit-readline-devel-20220411-r0: running post_install hook: 099_check_suid...
=> libedit-readline-devel-20220411-r0: running post_install hook: 100_rewrite_python_shebang...
=> libedit-readline-devel-20220411-r0: running post_install hook: 200_split_autopkgs...
=> libedit-readline-devel-static-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-readline-devel-20220411/usr/lib/libreadline.a -> /cports/bldroot-stage0/destdir/libedit-readline-devel-static-20220411
=> libedit-readline-devel-static-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-readline-devel-20220411/usr/lib/libhistory.a -> /cports/bldroot-stage0/destdir/libedit-readline-devel-static-20220411
=> libedit-readline-devel-20220411-r0: running post_install hook: 998_remove_empty_dirs...
=> libedit-readline-devel-20220411-r0: running post_install hook: 999_lint_devel...
=> libedit-devel-20220411-r0: running pkg_install...
=> libedit-devel-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-20220411/usr/lib/libedit.a -> /cports/bldroot-stage0/destdir/libedit-devel-20220411
=> libedit-devel-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-20220411/usr/lib/libedit.so -> /cports/bldroot-stage0/destdir/libedit-devel-20220411
=> libedit-devel-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-20220411/usr/lib/pkgconfig -> /cports/bldroot-stage0/destdir/libedit-devel-20220411
=> libedit-devel-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-20220411/usr/include -> /cports/bldroot-stage0/destdir/libedit-devel-20220411
=> libedit-devel-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-20220411/usr/share/man/man3 -> /cports/bldroot-stage0/destdir/libedit-devel-20220411
=> libedit-devel-20220411-r0: running post_install hook: 000_handle_modes...
=> libedit-devel-20220411-r0: running post_install hook: 001_hardlinks...
=> libedit-devel-20220411-r0: detecting hardlinks
=> libedit-devel-20220411-r0: running post_install hook: 002_uncompress_manpages...
=> libedit-devel-20220411-r0: running post_install hook: 003_remove_misc...
=> libedit-devel-20220411-r0: running post_install hook: 004_remove_libtool_archives...
=> libedit-devel-20220411-r0: running post_install hook: 005_remove_perl_files...
=> libedit-devel-20220411-r0: running post_install hook: 007_strip_debug...
   Stripped static library: usr/lib/libedit.a
=> libedit-devel-20220411-r0: running post_install hook: 008_rename_python_bindings...
=> libedit-devel-20220411-r0: running post_install hook: 009_remove_pkgconf_sysroot...
=> libedit-devel-20220411-r0: running post_install hook: 099_check_suid...
=> libedit-devel-20220411-r0: running post_install hook: 100_rewrite_python_shebang...
=> libedit-devel-20220411-r0: running post_install hook: 200_split_autopkgs...
=> libedit-devel-static-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-devel-20220411/usr/lib/libedit.a -> /cports/bldroot-stage0/destdir/libedit-devel-static-20220411
=> libedit-devel-man-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-devel-20220411/usr/share/man -> /cports/bldroot-stage0/destdir/libedit-devel-man-20220411
=> libedit-devel-20220411-r0: running post_install hook: 998_remove_empty_dirs...
=> WARNING: libedit-devel-20220411-r0: removed empty directory: usr/share
=> libedit-devel-20220411-r0: running post_install hook: 999_lint_devel...
=> libedit-20220411-r0: running post_install hook: 000_handle_modes...
=> libedit-20220411-r0: running post_install hook: 001_hardlinks...
=> libedit-20220411-r0: detecting hardlinks
=> libedit-20220411-r0: running post_install hook: 002_uncompress_manpages...
=> libedit-20220411-r0: running post_install hook: 003_remove_misc...
=> libedit-20220411-r0: running post_install hook: 004_remove_libtool_archives...
=> libedit-20220411-r0: running post_install hook: 005_remove_perl_files...
=> libedit-20220411-r0: running post_install hook: 007_strip_debug...
   Stripped library: usr/lib/libedit.so.0.0.0
=> libedit-20220411-r0: running post_install hook: 008_rename_python_bindings...
=> libedit-20220411-r0: running post_install hook: 009_remove_pkgconf_sysroot...
=> libedit-20220411-r0: running post_install hook: 099_check_suid...
=> libedit-20220411-r0: running post_install hook: 100_rewrite_python_shebang...
=> libedit-20220411-r0: running post_install hook: 200_split_autopkgs...
=> libedit-doc-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-20220411/usr/share/licenses -> /cports/bldroot-stage0/destdir/libedit-doc-20220411
=> libedit-man-20220411-r0: moving: /cports/bldroot-stage0/destdir/libedit-20220411/usr/share/man -> /cports/bldroot-stage0/destdir/libedit-man-20220411
=> libedit-20220411-r0: running post_install hook: 998_remove_empty_dirs...
=> WARNING: libedit-20220411-r0: removed empty directory: usr/share
=> libedit-20220411-r0: running post_install hook: 999_lint_devel...
=> libedit-readline-devel-20220411-r0: running pre_pkg hook: 001_runtime_deps...
   symlink: usr/lib/pkgconfig/libedit.pc <-> libedit-devel
=> libedit-readline-devel-20220411-r0: running pre_pkg hook: 002_cmd_provides...
=> libedit-readline-devel-20220411-r0: running pre_pkg hook: 003_pc_provides...
=> libedit-readline-devel-20220411-r0: running pre_pkg hook: 004_so_provides...
=> libedit-readline-devel-20220411-r0: running pre_pkg hook: 090_timestamps...
=> libedit-readline-devel-20220411-r0: setting mtimes to Wed Aug 11 22:15:46 2021
=> libedit-readline-devel-20220411-r0: running pre_pkg hook: 098_lint...
=> libedit-readline-devel-20220411-r0: running pre_pkg hook: 099_scriptlets...
=> libedit-readline-devel-20220411-r0: running pre_pkg hook: 999_collected_rdeps...
=> libedit-devel-20220411-r0: running pre_pkg hook: 001_runtime_deps...
=> libedit-devel-20220411-r0: ERROR: failed scanning .pc files (missing pkgconf?)
Traceback (most recent call last):
  File "/cports/src/runner.py", line 1213, in fire
    case "bootstrap": bootstrap(cmd)
  File "/cports/src/runner.py", line 422, in bootstrap
    build.build(tgt, rp, {}, opt_signkey)
  File "/cports/src/cbuild/core/build.py", line 57, in build
    if dependencies.install(
  File "/cports/src/cbuild/core/dependencies.py", line 418, in install
    build.build(
  File "/cports/src/cbuild/core/build.py", line 57, in build
    if dependencies.install(
  File "/cports/src/cbuild/core/dependencies.py", line 400, in install
    build.build(
  File "/cports/src/cbuild/core/build.py", line 118, in build
    prepkg.invoke(sp)
  File "/cports/src/cbuild/step/prepkg.py", line 11, in invoke
    template.call_pkg_hooks(pkg, "pre_pkg")
  File "/cports/src/cbuild/core/template.py", line 169, in call_pkg_hooks
    run_pkg_func(pkg, f[0], f"{stepn}_{f[1]}", f"{stepn} hook: {f[1]}")
  File "/cports/src/cbuild/core/template.py", line 164, in run_pkg_func
    func(pkg)
  File "/cports/src/cbuild/hooks/pre_pkg/001_runtime_deps.py", line 301, in invoke
    _scan_pc(pkg)
  File "/cports/src/cbuild/hooks/pre_pkg/001_runtime_deps.py", line 191, in _scan_pc
    scan_pc(f)
  File "/cports/src/cbuild/hooks/pre_pkg/001_runtime_deps.py", line 165, in scan_pc
    pkg.error("failed scanning .pc files (missing pkgconf?)")
  File "/cports/src/cbuild/core/template.py", line 187, in error
    raise errors.PackageException(msg, end, self, broken)
cbuild.core.errors.PackageException: failed scanning .pc files (missing pkgconf?)
Bootstrap failed!
```

corresponding `.pc` files:
```
$ find bldroot-stage0/destdir/ -ls | grep \.pc
   533896      4 -rw-r--r--   1 yopito   yopito        289 Aug 15 17:23 bldroot-stage0/destdir/libedit-devel-20220411/usr/lib/pkgconfig/libedit.pc
   533857      0 lrwxrwxrwx   1 yopito   yopito         10 Aug 12  2021 bldroot-stage0/destdir/libedit-readline-devel-20220411/usr/lib/pkgconfig/readline.pc -> libedit.pc
```

**Comment by yopito** [comment]
I think that symlink `readline.pc` to `libedit.pc` is the problem, since these 2 `.pc` files are not part of the same package, so symlink can't be resolved on scanning "flat" content of package `libedit-readline-devel` ?
