### ISSUE TITLE
`cbuild` traceback error when 'cbuild_cache' directory is missing

### ISSUE THREAD

**Issue by yvvki** [chimera-linux/cports#1508]
When trying to build a package before bootstraping, Python throws a traceback error instead of the error message: `=> cbuild: build root not found (have you boootstrapped?)`.

<details>

<summary>See the log here</summary>

```
Traceback (most recent call last):
  File "/home/synth/Projects/cports/src/runner.py", line 2219, in fire
    do_pkg(cmd)
  File "/home/synth/Projects/cports/src/runner.py", line 1548, in do_pkg
    rp = template.read_pkg(
         ^^^^^^^^^^^^^^^^^^
  File "/home/synth/Projects/cports/src/cbuild/core/template.py", line 2301, in read_pkg
    return from_module(modh, ret)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/synth/Projects/cports/src/cbuild/core/template.py", line 1910, in from_module
    and ret.is_built()
        ^^^^^^^^^^^^^^
  File "/home/synth/Projects/cports/src/cbuild/core/template.py", line 1131, in is_built
    with flock.lock(flock.apklock(archn)):
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/synth/Projects/cports/src/cbuild/util/flock.py", line 11, in lock
    fd = os.open(path, os.O_CREAT | os.O_WRONLY | os.O_TRUNC)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/synth/Projects/cports/cbuild_cache/apk-x86_64.lock'
```

</details>

This issue seems to be solved by making the 'cbuild_cache' directory.

Please consider making the directory when running `./cbuild pkg`.

**Comment by mikoxyz** [comment]
> Please consider making the directory when running ./cbuild pkg.

nah, i think the correct fix would be to do the build root check before running read_pkg()
