### ISSUE TITLE
crossbuild is broken: missing target arch to clang ?

### ISSUE THREAD

**Issue by yopito** [chimera-linux/cports#18]
trying to build zlib for aarch64 on (native) x86_64:
```
$ rm -rf /build/chimera/masterdir && ./cbuild.py binary-bootstrap && ./cbuild.py -a aarch64 pkg zlib
```
output:
```
...
=> cbuild: updating software in /build/chimera/masterdir masterdir...
=> cbuild: removing autodeps...
WARNING: Ignoring /binpkgs/nonfree: No such file or directory
WARNING: Ignoring /binpkgs/debug: No such file or directory
OK: 348 MiB in 60 packages
=> cbuild: removing autodeps...
=> base-cross-0.1-r0: found (base-cross-0.1-r0)
=> zlib-1.2.11-r0: installing cross toolchain for aarch64...
=> zlib-1.2.11-r0: setting up sysroot for aarch64...
=> zlib-1.2.11-r0: updating virtual provider for aarch64...
=> zlib-1.2.11-r0: building [configure] for x86_64...
   [runtime] zlib=1.2.11-r0: subpackage (ignored)
=> zlib-1.2.11-r0: running do_fetch hook: 00_distfiles...
=> zlib-1.2.11-r0: running do_extract hook: 00_distfiles...
=> zlib-1.2.11-r0: running init_patch hook: 00_env_pkg_config...
=> zlib-1.2.11-r0: running do_patch hook: 00_patches...
=> zlib-1.2.11-r0: patching: makefile_ranlib_syntax.patch
=> zlib-1.2.11-r0: running pre_configure hook: 02_script_wrapper...
=> zlib-1.2.11-r0: running do_configure...
Compiler error reporting is too harsh for /builddir/zlib-1.2.11/configure (perhaps remove -Werror).
** /builddir/zlib-1.2.11/configure aborting.
=> A failure has occured!
Traceback (most recent call last):
  File "/home/yopito/chimera/cports.git/./cbuild.py", line 390, in <module>
    ({
  File "/home/yopito/chimera/cports.git/./cbuild.py", line 381, in do_pkg
    build.build(tgt, rp, {}, opt_signkey)
  File "/home/yopito/chimera/cports.git/cbuild/core/build.py", line 42, in build
    configure.invoke(pkg, step)
  File "/home/yopito/chimera/cports.git/cbuild/step/configure.py", line 15, in invoke
    pkg.run_step("configure", optional = True)
  File "/home/yopito/chimera/cports.git/cbuild/core/template.py", line 648, in run_step
    if not run_pkg_func(self, "do_" + stepn) and not optional:
  File "/home/yopito/chimera/cports.git/cbuild/core/template.py", line 159, in run_pkg_func
    func(pkg)
  File "/home/yopito/chimera/cports.git/srcpkgs/zlib/template.py", line 15, in do_configure
    self.do(self.chroot_wrksrc / "configure", [
  File "/home/yopito/chimera/cports.git/cbuild/core/template.py", line 629, in do
    return chroot.enter(
  File "/home/yopito/chimera/cports.git/cbuild/core/chroot.py", line 419, in enter
    return subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bwrap', '--ro-bind', '/build/chimera/masterdir', '/', '--bind', '/build/chimera/masterdir/builddir', '/builddir', '--bind', '/build/chimera/masterdir/destdir', '/destdir', '--ro-bind', '/build/chimera/hostdir/sources', '/sources', '--dev', '/dev', '--proc', '/proc', '--tmpfs', '/tmp', '--bind', '/build/chimera/hostdir/ccache', '/ccache', '--unshare-all', '--chdir', '/builddir/zlib-1.2.11', '/builddir/zlib-1.2.11/configure', '--prefix=/usr', '--shared']' returned non-zero exit status 1.
```
more details in configure.log:
```
$ cat /build/chimera/masterdir/builddir/zlib-1.2.11/configure.log
--------------------
/builddir/zlib-1.2.11/configure --prefix=/usr --shared

=== ztest2.c ===
extern int getchar();
int hello() {return getchar();}
===
clang -c ztest2.c
... using gcc

Checking for obsessive-compulsive compiler options...
=== ztest2.c ===
int foo() { return 0; }
===
clang -c -D_FORTIFY_SOURCE=2 -fstack-protector-strong -march=armv8-a --sysroot /usr/aarch64-linux-musl ztest2.c
error: unknown target CPU 'armv8-a'
note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, tigerlake, sapphirerapids, alderlake, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, znver3, x86-64, x86-64-v2, x86-64-v3, x86-64-v4
(exit code 1)
Compiler error reporting is too harsh for /builddir/zlib-1.2.11/configure (perhaps remove -Werror).
** /builddir/zlib-1.2.11/configure aborting.
--------------------
```

**Comment by yopito** [comment]
using last git commit: 771992f
