### ISSUE TITLE
main/ca-certificates: build fails on stage0

### ISSUE THREAD

**Issue by yopito** [chimera-linux/cports#27]
`main/ca-certificates` is building fine on on regular workflow (with binpkgs from stage2) but currently fails on bootstraping stage0 (with rev e31ae19).

~~looks like that `post_patch` phase in this context is not within a bubblewrap chroot, so clang fails (see `-isystem` argument):~~

bootstraping stage0 output:
```
$ rm -rf masterdir-stage0/
$ BOOTSTRAP_ROOT=/build/chimera/SCRATCH_cports.git/bootstrap.ROOTDIR ./bootstrap.sh
[...]
=> cbuild: bootstrapping stage 0
=> base-chroot-0.66-r0: building for x86_64...
   [runtime] musl-devel>=0: found (1.2.2-r0)
   [runtime] base-files>=0: found (0.142-r0)
   [runtime] elftoolchain>=0: found (0.7.1_svn20210623-r0)
   [runtime] llvm>=0: found (12.0.0-r0)
   [runtime] clang>=0: found (12.0.0-r0)
   [runtime] lld>=0: found (12.0.0-r0)
   [runtime] bmake>=0: found (20210420-r0)
   [runtime] bsdutils>=0: found (0.0.1-r0)
   [runtime] dash>=0: found (0.5.11.3-r0)
   [runtime] file>=0: found (5.40-r0)
   [runtime] apk-tools>=0: not found
   [runtime] awk>=0: not found
   [runtime] ncurses>=0: found (6.2-r0)
   [runtime] bsdgrep>=0: not found
   [runtime] bsdgzip>=0: not found
   [runtime] bsdpatch>=0: not found
   [runtime] bsdsed>=0: not found
   [runtime] bsdtar>=0: found (3.5.1-r0)
   [runtime] bsddiff>=0: not found
   [runtime] chroot-util-linux>=0: not found
=> apk-tools-2.12.5-r0: building [meson] (dependency of base-chroot) for x86_64...
   [target] zlib-devel: found (1.2.11-r0)
   [target] openssl-devel: found (1.1.1k-r0)
   [runtime] ca-certificates>=0: not found
   [runtime] apk-tools=2.12.5-r0: subpackage (ignored)
=> ca-certificates-20210119-r0: building (dependency of apk-tools) for x86_64...
   [host] openssl: found (1.1.1k-r0)
   [runtime] openssl<=2.0: found (1.1.1k-r0)
   [runtime] run-parts>=0: found (4.11.2-r0)
=> ca-certificates-20210119-r0: installing host dependencies: openssl
=> ca-certificates-20210119-r0: running do_fetch hook: 00_distfiles...
=> ca-certificates-20210119-r0: running do_extract hook: 00_distfiles...
=> ca-certificates-20210119-r0: running init_patch hook: 00_env_pkg_config...
=> ca-certificates-20210119-r0: running do_patch hook: 00_patches...
=> ca-certificates-20210119-r0: patching: update-ca-certificates-destdir.patch
=> ca-certificates-20210119-r0: running post_patch...
clang -D_FORTIFY_SOURCE=2 -fstack-protector-strong -O2 -pipe -rtlib=compiler-rt -isystem /cports/masterdir-stage0/usr/include certdata2pem.c -Wl,--as-needed -Wl,-z,now -Wl,-z,relro -fuse-ld=lld -L/cports/masterdir-stage0/usr/lib -Wl,-rpath-link=/cports/masterdir-stage0/usr/lib -o /builddir/work/mozilla/certdata2pem
=> A failure has occured!
Traceback (most recent call last):
  File "/cports/cbuild.py", line 390, in <module>
    ({
  File "/cports/cbuild.py", line 265, in bootstrap
    build.build(tgt, rp, {}, opt_signkey)
  File "/cports/cbuild/core/build.py", line 34, in build
    autodep = dependencies.install(pkg, pkg.origin.pkgname, "pkg", depmap, signkey)
  File "/cports/cbuild/core/dependencies.py", line 410, in install
    build.build(step, template.read_pkg(
  File "/cports/cbuild/core/build.py", line 34, in build
    autodep = dependencies.install(pkg, pkg.origin.pkgname, "pkg", depmap, signkey)
  File "/cports/cbuild/core/dependencies.py", line 410, in install
    build.build(step, template.read_pkg(
  File "/cports/cbuild/core/build.py", line 58, in build
    patch.invoke(pkg)
  File "/cports/cbuild/step/patch.py", line 15, in invoke
    pkg.run_step("patch", optional = True)
  File "/cports/cbuild/core/template.py", line 620, in run_step
    run_pkg_func(self, "post_" + stepn)
  File "/cports/cbuild/core/template.py", line 160, in run_pkg_func
    func(pkg)
  File "/cports/main/ca-certificates/template.py", line 23, in post_patch
    cc.invoke(
  File "/cports/cbuild/util/compiler.py", line 36, in invoke
    return self.template.do(self.cexec, argsbase)
  File "/cports/cbuild/core/template.py", line 593, in do
    return chroot.enter(
  File "/cports/cbuild/core/chroot.py", line 359, in enter
    return subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/builddir/work'
Bootstrap failed!
```

**Comment by yopito** [comment]
display `self.cwd`  just before calling `cc.invoke` in `post_patch():`
```
=> ca-certificates-20210119-r0: (dbg) self.cwd=/cports/masterdir-stage0/builddir/work
```

**Comment by yopito** [comment]
moving `cc.invoke()` block into `init_build()` is working (at least for stage0).
BTW, this is strange to call compiler within post_patch() phase ?

**Comment by q66** [comment]
fixed
