### ISSUE TITLE
stage1: circular dependency between perl and gmake

### ISSUE THREAD

**Issue by yopito** [chimera-linux/cports#46]
using rev 0377753:

```
=> cbuild: bootstrapping stage 1
OK: 56 distinct packages available
=> base-chroot-0.1-r0: building [meta] for x86_64...
   [runtime] musl-devel>=0: not found
   [runtime] base-files>=0: not found
   [runtime] elftoolchain>=0: not found
   [runtime] llvm>=0: not found
   [runtime] clang>=0: not found
   [runtime] lld>=0: not found
   [runtime] bmake>=0: not found
   [runtime] bsdutils>=0: not found
   [runtime] dash>=0: not found
   [runtime] file>=0: not found
   [runtime] apk-tools>=0: not found
   [runtime] awk>=0: not found
   [runtime] ncurses>=0: not found
   [runtime] bsdgrep>=0: not found
   [runtime] bsdgzip>=0: not found
   [runtime] bsdpatch>=0: not found
   [runtime] bsdsed>=0: not found
   [runtime] bsdtar>=0: not found
   [runtime] bsddiff>=0: not found
   [runtime] chroot-util-linux>=0: not found
   [runtime] ccache>=0: not found
=> musl-1.2.2-r0: building [gnu_configure] (dependency of base-chroot) for x86_64...
   [host] gmake: not found
   [runtime] kernel-libc-headers>=0: not found
   [runtime] musl=1.2.2-r0: subpackage (ignored)
=> gmake-4.3-r0: building [gnu_configure] (dependency of musl) for x86_64...
   [host] perl: not found
=> perl-5.32.1-r0: building [gnu_configure] (dependency of gmake) for x86_64...
   [host] gmake: not found
=> perl-5.32.1-r0: [host] build loop detected: gmake <-> gmake
=> A failure has occured!
Traceback (most recent call last):
  File "/cports/./cbuild", line 481, in <module>
    case "bootstrap": bootstrap(cmd)
  File "/cports/./cbuild", line 350, in bootstrap
    do_pkg("pkg", "main/base-chroot", False, False)
  File "/cports/./cbuild", line 470, in do_pkg
    build.build(
  File "/cports/src/cbuild/core/build.py", line 50, in build
    dependencies.install(pkg, pkg.origin.pkgname, "pkg", depmap, signkey)
  File "/cports/src/cbuild/core/dependencies.py", line 414, in install
    build.build(step, template.read_pkg(
  File "/cports/src/cbuild/core/build.py", line 50, in build
    dependencies.install(pkg, pkg.origin.pkgname, "pkg", depmap, signkey)
  File "/cports/src/cbuild/core/dependencies.py", line 392, in install
    build.build(step, template.read_pkg(
  File "/cports/src/cbuild/core/build.py", line 50, in build
    dependencies.install(pkg, pkg.origin.pkgname, "pkg", depmap, signkey)
  File "/cports/src/cbuild/core/dependencies.py", line 392, in install
    build.build(step, template.read_pkg(
  File "/cports/src/cbuild/core/build.py", line 50, in build
    dependencies.install(pkg, pkg.origin.pkgname, "pkg", depmap, signkey)
  File "/cports/src/cbuild/core/dependencies.py", line 321, in install
    pkg.error(f"[host] build loop detected: {pkgn} <-> {origpkg}")
  File "/cports/src/cbuild/core/template.py", line 185, in error
    raise PackageError()
cbuild.core.template.PackageError
Bootstrap failed!
```

**Comment by yopito** [comment]
because neither `perl` nor `gmake` are built on stage0 ?
