### ISSUE TITLE
cbuild cross failures if deps have to be built before specified pkg

### ISSUE THREAD

**Issue by JamiKettunen** [chimera-linux/cports#475]
From https://github.com/JamiKettunen/cports/tree/android-tools (after rebasing on latest `master`) attempting e.g. `./cbuild -a riscv64 pkg contrib/protobuf` fails with:
```
=> protobuf-24.2-r0: installing host dependencies: cmake=3.27.4-r0, ninja=1.11.1-r0, pkgconf=2.0.3-r0, base-cross-riscv64=0.1-r1, protobuf=24.2-r0
=> protobuf-24.2-r0: installing target dependencies: zlib-devel=1.3-r0, gtest-devel=1.14.0-r0, abseil-cpp-devel=20230802.0-r1
=> cbuild: updating software in /path/to/cports/bldroot container...
OK: 624 MiB in 82 packages
=> protobuf-24.2-r0: running do_extract hook: 000_sources...
tee: /path/to/cports/bldroot/builddir/.cbuild-protobuf/protobuf_riscv64_do_extract_000_sources.log: No such file or directory
=> A failure has occurred!
Traceback (most recent call last):
  File "/path/to/cports/src/runner.py", line 2198, in fire
    do_pkg(cmd)
  File "/path/to/cports/src/runner.py", line 1555, in do_pkg
    build.build(
  File "/path/to/cports/src/cbuild/core/build.py", line 98, in build
    extract.invoke(pkg)
  File "/path/to/cports/src/cbuild/step/extract.py", line 27, in invoke
    extract_done.touch()
  File "/usr/lib/python3.11/pathlib.py", line 1108, in touch
    fd = os.open(self, flags, mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/cports/bldroot/builddir/.cbuild-protobuf/protobuf_riscv64_extract_done'
```
(full log: https://paste.c-net.org/mcipysx7n2wj)

But that's not all, the original issue I saw which is reproducible with a clean `packages/` & `pkgstage/` is after the above succeeds is `./cbuild -a riscv64 pkg contrib/android-tools` failing like:
```
=> android-tools-34.0.4-r0: installing host dependencies: cmake=3.27.4-r0, ninja=1.11.1-r0, perl=5.36.1-r0, go=1.21.0-r2, pkgconf=2.0.3-r0, protobuf=24.2-r0, base-cross-riscv64=0.1-r1
=> android-tools-34.0.4-r0: installing target dependencies: brotli-devel=1.1.0-r0, liblz4-devel=1.9.4-r0, pcre2-devel=10.42-r0, libusb-devel=1.0.26-r0, libzstd-devel=1.5.5-r0, protobuf-devel=24.2-r0, linux-headers=6.1.19-r0, gtest-devel=1.14.0-r0
=> cbuild: updating software in /path/to/cports/bldroot container...
OK: 514 MiB in 62 packages
=> android-tools-34.0.4-r0: running do_extract hook: 000_sources...
=> android-tools-34.0.4-r0: running do_patch hook: 000_patches...
=> android-tools-34.0.4-r0: running pre_configure hook: 000_script_wrapper...
=> android-tools-34.0.4-r0: running pre_configure hook: 001_prepare_users...
=> android-tools-34.0.4-r0: running do_configure...
linux64: execvp: No such file or directory
=> A failure has occurred!
Traceback (most recent call last):
  File "/path/to/cports/src/runner.py", line 2198, in fire
    do_pkg(cmd)
  File "/path/to/cports/src/runner.py", line 1555, in do_pkg
    build.build(
  File "/path/to/cports/src/cbuild/core/build.py", line 116, in build
    configure.invoke(pkg, step)
  File "/path/to/cports/src/cbuild/step/configure.py", line 15, in invoke
    pkg.run_step("configure", optional=True)
  File "/path/to/cports/src/cbuild/core/template.py", line 1253, in run_step
    if not run_pkg_func(self, "do_" + stepn) and not optional:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/cports/src/cbuild/core/template.py", line 169, in run_pkg_func
    func(pkg)
  File "/path/to/cports/src/cbuild/build_style/cmake.py", line 5, in do_configure
    cmake.configure(self, self.cmake_dir)
  File "/path/to/cports/src/cbuild/util/cmake.py", line 88, in configure
    pkg.do(
  File "/path/to/cports/src/cbuild/core/template.py", line 1223, in do
    return chroot.enter(
           ^^^^^^^^^^^^^
  File "/path/to/cports/src/cbuild/core/chroot.py", line 756, in enter
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bwrap', '--unshare-all', '--hostname', 'cbuild', '--ro-bind', PosixPath('/path/to/cports/bldroot'), '/', '--bind', PosixPath('/path/to/cports/bldroot/builddir'), '/builddir', '--ro-bind', PosixPath('/path/to/cports/bldroot/destdir'), '/destdir', '--ro-bind', PosixPath('/path/to/cports/sources'), '/sources', '--dev', '/dev', '--proc', '/proc', '--tmpfs', '/tmp', '--tmpfs', '/var/tmp', '--new-session', '--die-with-parent', '--bind', PosixPath('/path/to/cports/cbuild_cache'), '/cbuild_cache', '--uid', '1337', '--gid', '1337', '--chdir', PosixPath('/builddir/android-tools-34.0.4/build'), '--ro-bind-data', '5', '/tmp/cbuild-lld-args', 'linux64', '--', 'cmake', '-DCMAKE_TOOLCHAIN_FILE=cross.cmake', '-DCMAKE_AR=/usr/bin/llvm-ar', '-DCMAKE_NM=/usr/bin/llvm-nm', '-DCMAKE_RANLIB=/usr/bin/llvm-ranlib', '-DCMAKE_INSTALL_PREFIX=/usr', '-DCMAKE_BUILD_TYPE=None', '-DCMAKE_INSTALL_LIBDIR=lib', '-DCMAKE_INSTALL_SBINDIR=bin', PosixPath('/builddir/android-tools-34.0.4')]' returned non-zero exit status 1.
```
(full log: https://paste.c-net.org/ow3gbablwzpy)

Simply retrying the same commands made both of these issues not appear and it proceeded to running the build steps (tho in case of the 2nd one it'll fail anyway for a protobuf packaging related reason); so far I've not seen anything like this for the native builds.

**Comment by JamiKettunen** [comment]
I think it doesn't actually properly install host dependencies despite saying so; while I see e.g. `/usr/riscv64-chimera-linux-musl/usr/lib/pkgconfig/libbrotlicommon.pc` existing in the bldroot `autodeps-host` only depends on `base-cross-riscv64=0.1-r1` (after failure entering chroot)

**Comment by q66** [comment]
i think this may mostly be fixed, feel free to reopen if not
