### ISSUE TITLE
libxo: fails to build on stage0

### ISSUE THREAD

**Issue by yopito** [chimera-linux/cports#48]
using rev 56a5fe1 :

```
...
=> gettext-tiny-devel-0.3.2-r0: removing files from destdir...
=> libxo-1.6.0-r0: installing target dependencies: gettext-tiny-devel
=> libxo-1.6.0-r0: running do_fetch hook: 00_sources...
=> libxo-1.6.0-r0: running do_extract hook: 00_sources...
=> libxo-1.6.0-r0: running init_patch hook: 00_env_pkg_config...
=> libxo-1.6.0-r0: running do_patch hook: 00_patches...
=> libxo-1.6.0-r0: patching: bmake.patch
=> libxo-1.6.0-r0: patching: gettext.patch
=> libxo-1.6.0-r0: patching: portability.patch
=> libxo-1.6.0-r0: running post_patch...
=> libxo-1.6.0-r0: running pre_configure hook: 02_script_wrapper...
=> libxo-1.6.0-r0: running do_configure...
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether clang accepts -g... yes
checking for clang option to enable C11 features... none needed
checking whether clang understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of clang... none
checking whether ln -s works... yes
checking build system type... x86_64-pc-linux-musl
checking host system type... x86_64-pc-linux-musl
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by clang... ld.lld
checking if the linker (ld.lld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... nm
checking the name lister (nm) interface... BSD nm
checking the maximum length of command line arguments... 98304
checking how to convert x86_64-pc-linux-musl file names to x86_64-pc-linux-musl format... func_convert_file_noop
checking how to convert x86_64-pc-linux-musl file names to toolchain format... func_convert_file_noop
checking for ld.lld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse nm output from clang object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if clang supports -fno-rtti -fno-exceptions... yes
checking for clang option to produce PIC... -fPIC -DPIC
checking if clang PIC flag -fPIC -DPIC works... yes
checking if clang static flag -static works... yes
checking if clang supports -c -o file.o... yes
checking if clang supports -c -o file.o... (cached) yes
checking whether the clang linker (ld.lld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... yes
checking whether a program can dlopen itself... yes
checking whether a statically linked program can dlopen itself... no
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for basename... /usr/bin/basename
checking for bison... /usr/bin/bison
checking for cat... /usr/bin/cat
checking for chmod... /usr/bin/chmod
checking for cp... /usr/bin/cp
checking for diff... /usr/bin/diff
checking for mkdir... /usr/bin/mkdir
checking for mv... /usr/bin/mv
checking for rm... /usr/bin/rm
checking for sed... (cached) /usr/bin/sed
checking for inline... inline
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking for GNU libc compatible malloc... yes
checking for GNU libc compatible realloc... yes
checking for bzero... yes
checking for memmove... yes
checking for strchr... yes
checking for strcspn... yes
checking for strerror... yes
checking for strspn... yes
checking for sranddev... no
checking for srand... yes
checking for strlcpy... yes
checking for fdopen... yes
checking for getrusage... yes
checking for gettimeofday... yes
checking for ctime... yes
checking for getpass... yes
checking for getprogname... no
checking for sysctlbyname... no
checking for flock... yes
checking for asprintf... yes
checking for __flbf... yes
checking for sysctlbyname... (cached) no
checking for dlfcn.h... (cached) yes
checking for dlfcn.h... (cached) yes
checking for stdio_ext.h... yes
checking for tzfile.h... no
checking for stdtime/tzfile.h... no
checking for dlfunc... no
checking for sys/time.h... yes
checking for ctype.h... yes
checking for errno.h... yes
checking for stdio.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for sys/param.h... yes
checking for unistd.h... (cached) yes
checking for sys/sysctl.h... no
checking for threads.h... yes
checking for monitor.h... no
checking for libutil.h... no
checking for humanize_number in -lutil... no
humanize_number results: :no:no:
checking gettext in /usr... yes
checking thread-locals are unknown... before
checking for MD5_Init in -lcrypto... no
checking for struct sockaddr_un.sun_len... no
checking for clang options needed to detect all undeclared functions... -fno-builtin
checking whether __isthreaded is declared... no
checking for libslax... no
checking whether to build with warnings... no
checking whether to build with debugging... no
checking whether to use int return codes... no
checking whether to build with text-only rendering... no
checking whether to build with local wcwidth implementation... yes
checking retain hash bucket size... default
checking for lrint in -lm... yes
checking compiler for gcc... no
checking whether to build with printflike... no
checking whether to build with LIBXO_OPTIONS... yes
Using configure dir /cports/bldroot-stage0/builddir/libxo-1.6.0
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libxo-config
config.status: creating xohtml/xohtml.sh
config.status: creating libxo/Makefile
config.status: creating libxo/add.man
config.status: creating bin/Makefile
config.status: creating encoder/Makefile
config.status: creating encoder/cbor/Makefile
config.status: creating encoder/csv/Makefile
config.status: creating encoder/test/Makefile
config.status: creating xo/Makefile
config.status: creating xolint/Makefile
config.status: creating xohtml/Makefile
config.status: creating xopo/Makefile
config.status: creating packaging/libxo.pc
config.status: creating doc/Makefile
config.status: creating doc/top-link.html
config.status: creating tests/Makefile
config.status: creating tests/core/Makefile
config.status: creating tests/gettext/Makefile
config.status: creating tests/xo/Makefile
config.status: creating packaging/libxo.spec
config.status: creating packaging/libxo.rb.base
config.status: creating libxo/xo_config.h
config.status: executing depfiles commands
config.status: executing libtool commands
rm: cannot remove 'libtoolT': No such file or directory
configure: summary of build options:

  libxo version:    1.6.0 
  host type:        x86_64-pc-linux-musl / linux-musl
  install prefix:   /usr
  srcdir:           /cports/bldroot-stage0/builddir/libxo-1.6.0
  libdir:           /usr/lib
  bindir:           /usr/bin
  includedir:       ${prefix}/include
  share dir:        /usr/share/libxo
  extensions dir:   /usr/lib/libxo/encoder
  oxtradoc dir:     

  compiler:         clang (no)
  compiler flags:   -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstack-clash-protection -Wno-unused-command-line-argument -O2 -pipe -rtlib=compiler-rt -isystem /cports/bldroot-stage0/usr/include
  library types:    Shared=yes, Static=yes

  warnings:         no
  debug:            no
  printf-like:      no
  libxo-options:    yes
  text-only:        no
  gettext:          yes (/usr)
  isthreaded:       no
  thread-local:     before
  local wcwidth:    yes
  retain size:      default

=> libxo-1.6.0-r0: running do_build...
--- all-recursive ---
Making all in bin
Making all in libxo
--- all ---
bmake  all-am
--- libxo.lo ---
--- xo_encoder.lo ---
--- xo_syslog.lo ---
--- libxo.lo ---
  CC       libxo.lo
--- xo_encoder.lo ---
  CC       xo_encoder.lo
--- xo_syslog.lo ---
  CC       xo_syslog.lo
--- libxo.la ---
  CCLD     libxo.la
/usr/bin/x86_64-unknown-linux-musl-ld: cannot find -lintl
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
*** [libxo.la] Error code 1

bmake[2]: stopped in /cports/bldroot-stage0/builddir/libxo-1.6.0/build/libxo
1 error

bmake[2]: stopped in /cports/bldroot-stage0/builddir/libxo-1.6.0/build/libxo

bmake[1]: stopped in /cports/bldroot-stage0/builddir/libxo-1.6.0/build/libxo

bmake: stopped in /cports/bldroot-stage0/builddir/libxo-1.6.0/build
=> A failure has occured!
Traceback (most recent call last):
  File "/cports/./cbuild", line 491, in <module>
    case "bootstrap": bootstrap(cmd)
  File "/cports/./cbuild", line 343, in bootstrap
    build.build(tgt, rp, {}, opt_signkey)
  File "/cports/src/cbuild/core/build.py", line 50, in build
    dependencies.install(pkg, pkg.origin.pkgname, "pkg", depmap, signkey)
  File "/cports/src/cbuild/core/dependencies.py", line 415, in install
    build.build(step, template.read_pkg(
  File "/cports/src/cbuild/core/build.py", line 50, in build
    dependencies.install(pkg, pkg.origin.pkgname, "pkg", depmap, signkey)
  File "/cports/src/cbuild/core/dependencies.py", line 403, in install
    build.build(step, template.read_pkg(
  File "/cports/src/cbuild/core/build.py", line 84, in build
    buildm.invoke(pkg, step)
  File "/cports/src/cbuild/step/build.py", line 13, in invoke
    pkg.run_step("build", optional = True)
  File "/cports/src/cbuild/core/template.py", line 883, in run_step
    if not run_pkg_func(self, "do_" + stepn) and not optional:
  File "/cports/src/cbuild/core/template.py", line 161, in run_pkg_func
    func(pkg)
  File "/cports/src/cbuild/build_style/gnu_configure.py", line 8, in do_build
    self.make.build()
  File "/cports/src/cbuild/util/make.py", line 67, in build
    return self.invoke(
  File "/cports/src/cbuild/util/make.py", line 60, in invoke
    return self.template.do(
  File "/cports/src/cbuild/core/template.py", line 861, in do
    return chroot.enter(
  File "/cports/src/cbuild/core/chroot.py", line 384, in enter
    return subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bmake', '-j3']' returned non-zero exit status 2.
Bootstrap failed!
```

**Comment by yopito** [comment]
package `gettext-tiny` provides only static lib for libintl ?

```
$ 2> /dev/null tar tzf packages-stage0/main/x86_64/gettext-tiny-devel-0.3.2-r0.apk  | grep intl
usr/lib/libintl.a
usr/share/aclocal/intl.m4
usr/share/aclocal/intldir.m4
usr/share/aclocal/intlmacosx.m4
usr/share/gettext-tiny/m4/intl.m4
usr/share/gettext-tiny/m4/intldir.m4
usr/share/gettext-tiny/m4/intlmacosx.m4
```

**Comment by yopito** [comment]
thanks, fine with rev 15668d6.
I did not restart stage0 from scratch, only some clenup and relaunch it:
```
$ rm packages-stage0/main/x86_64/gettext-tiny-*
$ rm -rf bldroot-stage0
$ BOOTSTRAP_ROOT=/build/chimera/SCRATCH_cports.git/bootstrap.ROOTDIR ./bootstrap.sh
```
