### ISSUE TITLE
ncurses build fails on stage1

### ISSUE THREAD

**Issue by yopito** [chimera-linux/cports#57]
output:
```
...
=> ncurses-6.3-r0: building [gnu_configure] (dependency of less) for x86_64...
   [host] pkgconf: found (1.8.0-r0)
   [host] gmake: found (4.3-r0)
   [runtime] ncurses-base=6.3-r0: subpackage (ignored)
   [runtime] ncurses-devel=6.3-r0: subpackage (ignored)
   [runtime] ncurses-base=6.3-r0: subpackage (ignored)
=> ncurses-6.3-r0: installing host dependencies: pkgconf, gmake
=> ncurses-6.3-r0: running do_fetch hook: 00_sources...
=> ncurses-6.3-r0: running do_extract hook: 00_sources...
=> ncurses-6.3-r0: running init_patch hook: 00_env_pkg_config...
=> ncurses-6.3-r0: running do_patch hook: 00_patches...
=> ncurses-6.3-r0: running init_configure...
=> ncurses-6.3-r0: running pre_configure hook: 02_script_wrapper...
=> ncurses-6.3-r0: running do_configure...
checking for ggrep... no
checking for grep... grep
checking for egrep... grep -E
Configuring NCURSES 6.3 ABI 6 (Fri Nov 19 12:33:45 UTC 2021)
checking for package version... 6.3
checking for package patch date... 20211021
checking build system type... x86_64-pc-linux-musl
checking host system type... x86_64-pc-linux-musl
checking target system type... x86_64-pc-linux-musl
Configuring for linux-musl
checking for fgrep... grep -F
checking for prefix... /usr
checking for x86_64-linux-musl-gcc... clang
checking for C compiler default output... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for executable suffix... 
checking for object suffix... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking version of clang... 13.0.0
checking if this is really Intel C compiler... no
checking if this is really Clang C compiler... yes
checking version of clang... 13.0.0
checking if option -Qunused-arguments works... yes
checking if option -Wno-error=implicit-function-declaration works... yes
checking for clang option to accept ANSI C... none needed
checking $CFLAGS variable... broken
configure: WARNING: your environment uses the CFLAGS variable to hold CPPFLAGS options
checking $CC variable... ok
checking how to run the C preprocessor... clang-cpp
checking whether clang needs -traditional... no
checking whether clang understands -c and -o together... yes
checking for ldconfig... /usr/bin/ldconfig
checking if you want to ensure bool is consistent with C++... yes
checking for x86_64-linux-musl-g++... clang++
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking if clang++ works... yes
checking version of clang++... 13.0.0
checking if you want to build C++ binding and demo... yes
checking if you want to build with Ada... no
checking if you want to install terminal database... yes
checking if you want to install manpages... yes
checking if you want to build programs such as tic... yes
checking if you want to build test-programs... yes
checking if you wish to install curses.h... yes
checking for mawk... no
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking for a BSD compatible install... /usr/bin/install -c
checking for lint... no
checking for cppcheck... no
checking for splint... no
checking whether ln -s works... yes
checking if ln -s -f options work... yes
checking for long file names... yes
checking if you want to use pkg-config... yes
checking for x86_64-linux-musl-pkg-config... no
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for /usr/bin/pkg-config library directory... checking for first directory... none
checking if we should install .pc files for /usr/bin/pkg-config... yes
configure: error: expected a pathname, not ""
=> A failure has occured!
Traceback (most recent call last):
  File "/cports/src/runner.py", line 870, in fire
    case "bootstrap": bootstrap(cmd)
  File "/cports/src/runner.py", line 358, in bootstrap
    do_pkg("pkg", "main/base-cbuild", False, False, stage = 1)
  File "/cports/src/runner.py", line 816, in do_pkg
    build.build(
  File "/cports/src/cbuild/core/build.py", line 50, in build
    dependencies.install(pkg, pkg.origin.pkgname, "pkg", depmap, signkey)
  File "/cports/src/cbuild/core/dependencies.py", line 434, in install
    build.build(step, template.read_pkg(
  File "/cports/src/cbuild/core/build.py", line 50, in build
    dependencies.install(pkg, pkg.origin.pkgname, "pkg", depmap, signkey)
  File "/cports/src/cbuild/core/dependencies.py", line 422, in install
    build.build(step, template.read_pkg(
  File "/cports/src/cbuild/core/build.py", line 50, in build
    dependencies.install(pkg, pkg.origin.pkgname, "pkg", depmap, signkey)
  File "/cports/src/cbuild/core/dependencies.py", line 422, in install
    build.build(step, template.read_pkg(
  File "/cports/src/cbuild/core/build.py", line 50, in build
    dependencies.install(pkg, pkg.origin.pkgname, "pkg", depmap, signkey)
  File "/cports/src/cbuild/core/dependencies.py", line 422, in install
    build.build(step, template.read_pkg(
  File "/cports/src/cbuild/core/build.py", line 50, in build
    dependencies.install(pkg, pkg.origin.pkgname, "pkg", depmap, signkey)
  File "/cports/src/cbuild/core/dependencies.py", line 410, in install
    build.build(step, template.read_pkg(
  File "/cports/src/cbuild/core/build.py", line 50, in build
    dependencies.install(pkg, pkg.origin.pkgname, "pkg", depmap, signkey)
  File "/cports/src/cbuild/core/dependencies.py", line 410, in install
    build.build(step, template.read_pkg(
  File "/cports/src/cbuild/core/build.py", line 50, in build
    dependencies.install(pkg, pkg.origin.pkgname, "pkg", depmap, signkey)
  File "/cports/src/cbuild/core/dependencies.py", line 422, in install
    build.build(step, template.read_pkg(
  File "/cports/src/cbuild/core/build.py", line 80, in build
    configure.invoke(pkg, step)
  File "/cports/src/cbuild/step/configure.py", line 15, in invoke
    pkg.run_step("configure", optional = True)
  File "/cports/src/cbuild/core/template.py", line 990, in run_step
    if not run_pkg_func(self, "do_" + stepn) and not optional:
  File "/cports/src/cbuild/core/template.py", line 162, in run_pkg_func
    func(pkg)
  File "/cports/src/cbuild/build_style/gnu_configure.py", line 5, in do_configure
    gnu_configure.configure(self)
  File "/cports/src/cbuild/util/gnu_configure.py", line 126, in configure
    pkg.do(
  File "/cports/src/cbuild/core/template.py", line 968, in do
    return chroot.enter(
  File "/cports/src/cbuild/core/chroot.py", line 397, in enter
    return subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bwrap', '--unshare-all', '--hostname', 'cbuild', '--ro-bind', PosixPath('/cports/bldroot-stage0'), '/', '--bind', PosixPath('/cports/bldroot-stage0/builddir'), '/builddir', '--ro-bind', PosixPath('/cports/bldroot-stage0/destdir'), '/destdir', '--ro-bind', PosixPath('/cports/sources'), '/sources', '--dev', '/dev', '--proc', '/proc', '--tmpfs', '/tmp', '--tmpfs', '/var/tmp', '--new-session', '--die-with-parent', '--bind', PosixPath('/cports/ccache'), '/ccache', '--uid', '1337', '--gid', '1337', '--chdir', PosixPath('/builddir/ncurses-6.3/build'), PosixPath('/builddir/ncurses-6.3/configure'), '--prefix=/usr', '--sysconfdir=/etc', '--sbindir=/usr/bin', '--bindir=/usr/bin', '--libdir=/usr/lib', '--mandir=/usr/share/man', '--infodir=/usr/share/info', '--localstatedir=/var', '--build=x86_64-linux-musl', '--host=x86_64-linux-musl', '--enable-widec', '--enable-big-core', '--enable-ext-colors', '--enable-pc-files', '--without-debug', '--without-ada', '--with-shared', '--with-manpage-symlinks', '--with-manpage-format=normal', '--with-pkg-config-libdir=/usr/lib/pkgconfig', 'ac_cv_path_ac_pt_PKG_CONFIG=/usr/bin/pkg-config', 'BUILD_CFLAGS=-D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstack-clash-protection -O2 -fPIC']' returned non-zero exit status 1.
Bootstrap failed!
```

**Comment by q66** [comment]
oh, i bet it's this https://ariadne.space/2021/10/25/dont-do-clever-things-in-configure-scripts/

**Comment by yopito** [comment]
in `main/ncurses/template.py` , `configure_args`:
```
 10     "--with-pkg-config-libdir=/usr/lib/pkgconfig",
```
but `/usr/lib/pkgconf/` does not exist:
```
$ find bldroot-stage0/usr/lib/pkgconfig
find: ‘bldroot-stage0/usr/lib/pkgconfig’: No such file or directory
```
should `pkgconf` package should provides this empty dir ?

**Comment by yopito** [comment]
@q66: yes, `configure` script is really close to this madness :(
