### ISSUE TITLE
main/pkgconf: packaging fails on stage1

### ISSUE THREAD

**Issue by yopito** [chimera-linux/cports#75]
using rev a884684b:
```
...
=> pkgconf-1.8.0-r0: running post_install...
=> libpkgconf-1.8.0-r0: running pkg_install...
=> libpkgconf-1.8.0-r0: moving: /cports/bldroot-stage0/destdir/pkgconf-1.8.0/usr/lib/libpkgconf.so.3 -> /cports/bldroot-stage0/destdir/libpkgconf-1.8.0
=> libpkgconf-1.8.0-r0: moving: /cports/bldroot-stage0/destdir/pkgconf-1.8.0/usr/lib/libpkgconf.so.3.0.0 -> /cports/bldroot-stage0/destdir/libpkgconf-1.8.0
=> libpkgconf-1.8.0-r0: running post_install hook: 000_handle_modes...
=> libpkgconf-1.8.0-r0: running post_install hook: 001_hardlinks...
=> libpkgconf-1.8.0-r0: detecting hardlinks
=> libpkgconf-1.8.0-r0: running post_install hook: 002_uncompress_manpages...
=> libpkgconf-1.8.0-r0: running post_install hook: 003_remove_misc...
=> libpkgconf-1.8.0-r0: running post_install hook: 004_remove_libtool_archives...
=> libpkgconf-1.8.0-r0: running post_install hook: 005_remove_perl_files...
=> libpkgconf-1.8.0-r0: running post_install hook: 006_remove_python_bytecode...
=> libpkgconf-1.8.0-r0: running post_install hook: 007_strip_debug...
   Stripped library: usr/lib/libpkgconf.so.3.0.0
=> libpkgconf-1.8.0-r0: running post_install hook: 008_rename_python_bindings...
=> libpkgconf-1.8.0-r0: running post_install hook: 009_remove_pkgconf_sysroot...
=> libpkgconf-1.8.0-r0: running post_install hook: 099_check_suid...
=> libpkgconf-1.8.0-r0: running post_install hook: 100_rewrite_python_shebang...
=> libpkgconf-1.8.0-r0: running post_install hook: 199_remove_empty_dirs...
=> libpkgconf-1.8.0-r0: running post_install hook: 200_split_autopkgs...
=> libpkgconf-1.8.0-r0: running post_install hook: 999_lint_devel...
=> pkgconf-devel-1.8.0-r0: running pkg_install...
=> pkgconf-devel-1.8.0-r0: moving: /cports/bldroot-stage0/destdir/pkgconf-1.8.0/usr/include -> /cports/bldroot-stage0/destdir/pkgconf-devel-1.8.0
=> pkgconf-devel-1.8.0-r0: moving: /cports/bldroot-stage0/destdir/pkgconf-1.8.0/usr/lib/pkgconfig -> /cports/bldroot-stage0/destdir/pkgconf-devel-1.8.0
=> pkgconf-devel-1.8.0-r0: moving: /cports/bldroot-stage0/destdir/pkgconf-1.8.0/usr/lib/libpkgconf.so -> /cports/bldroot-stage0/destdir/pkgconf-devel-1.8.0
=> pkgconf-devel-1.8.0-r0: moving: /cports/bldroot-stage0/destdir/pkgconf-1.8.0/usr/lib/libpkgconf.a -> /cports/bldroot-stage0/destdir/pkgconf-devel-1.8.0
=> pkgconf-devel-1.8.0-r0: running post_install hook: 000_handle_modes...
=> pkgconf-devel-1.8.0-r0: running post_install hook: 001_hardlinks...
=> pkgconf-devel-1.8.0-r0: detecting hardlinks
=> pkgconf-devel-1.8.0-r0: running post_install hook: 002_uncompress_manpages...
=> pkgconf-devel-1.8.0-r0: running post_install hook: 003_remove_misc...
=> pkgconf-devel-1.8.0-r0: running post_install hook: 004_remove_libtool_archives...
=> pkgconf-devel-1.8.0-r0: running post_install hook: 005_remove_perl_files...
=> pkgconf-devel-1.8.0-r0: running post_install hook: 006_remove_python_bytecode...
=> pkgconf-devel-1.8.0-r0: running post_install hook: 007_strip_debug...
   Stripped static library: usr/lib/libpkgconf.a
=> pkgconf-devel-1.8.0-r0: running post_install hook: 008_rename_python_bindings...
=> pkgconf-devel-1.8.0-r0: running post_install hook: 009_remove_pkgconf_sysroot...
=> pkgconf-devel-1.8.0-r0: running post_install hook: 099_check_suid...
=> pkgconf-devel-1.8.0-r0: running post_install hook: 100_rewrite_python_shebang...
=> pkgconf-devel-1.8.0-r0: running post_install hook: 199_remove_empty_dirs...
=> pkgconf-devel-1.8.0-r0: running post_install hook: 200_split_autopkgs...
=> pkgconf-devel-static-1.8.0-r0: moving: /cports/bldroot-stage0/destdir/pkgconf-devel-1.8.0/usr/lib/libpkgconf.a -> /cports/bldroot-stage0/destdir/pkgconf-devel-static-1.8.0
=> pkgconf-devel-1.8.0-r0: running post_install hook: 999_lint_devel...
=> pkgconf-1.8.0-r0: running post_install hook: 000_handle_modes...
=> pkgconf-1.8.0-r0: running post_install hook: 001_hardlinks...
=> pkgconf-1.8.0-r0: detecting hardlinks
=> pkgconf-1.8.0-r0: running post_install hook: 002_uncompress_manpages...
=> pkgconf-1.8.0-r0: running post_install hook: 003_remove_misc...
=> pkgconf-1.8.0-r0: running post_install hook: 004_remove_libtool_archives...
=> pkgconf-1.8.0-r0: running post_install hook: 005_remove_perl_files...
=> pkgconf-1.8.0-r0: running post_install hook: 006_remove_python_bytecode...
=> pkgconf-1.8.0-r0: running post_install hook: 007_strip_debug...
   Stripped position-independent executable: usr/bin/pkgconf
=> pkgconf-1.8.0-r0: running post_install hook: 008_rename_python_bindings...
=> pkgconf-1.8.0-r0: running post_install hook: 009_remove_pkgconf_sysroot...
=> pkgconf-1.8.0-r0: running post_install hook: 099_check_suid...
=> pkgconf-1.8.0-r0: running post_install hook: 100_rewrite_python_shebang...
=> pkgconf-1.8.0-r0: running post_install hook: 199_remove_empty_dirs...
=> WARNING: pkgconf-1.8.0-r0: removed empty directory: usr/lib
=> pkgconf-1.8.0-r0: running post_install hook: 200_split_autopkgs...
=> pkgconf-doc-1.8.0-r0: moving: /cports/bldroot-stage0/destdir/pkgconf-1.8.0/usr/share/doc -> /cports/bldroot-stage0/destdir/pkgconf-doc-1.8.0
=> pkgconf-doc-1.8.0-r0: moving: /cports/bldroot-stage0/destdir/pkgconf-1.8.0/usr/share/licenses -> /cports/bldroot-stage0/destdir/pkgconf-doc-1.8.0
=> pkgconf-man-1.8.0-r0: moving: /cports/bldroot-stage0/destdir/pkgconf-1.8.0/usr/share/man -> /cports/bldroot-stage0/destdir/pkgconf-man-1.8.0
=> pkgconf-1.8.0-r0: running post_install hook: 999_lint_devel...
=> WARNING: pkgconf-1.8.0-r0: usr/share/aclocal should be in the -devel package
=> WARNING: pkgconf-1.8.0-r0: *-config tools should be in the -devel package
=> libpkgconf-1.8.0-r0: running pre_pkg hook: 001_runtime_deps...
   SONAME: libc.so <-> musl
=> libpkgconf-1.8.0-r0: running pre_pkg hook: 002_cmd_provides...
=> libpkgconf-1.8.0-r0: running pre_pkg hook: 003_pc_provides...
=> libpkgconf-1.8.0-r0: running pre_pkg hook: 004_so_provides...
   SONAME libpkgconf.so.3 from usr/lib
=> libpkgconf-1.8.0-r0: running pre_pkg hook: 090_timestamps...
=> libpkgconf-1.8.0-r0: setting mtimes to Tue Dec 28 00:58:00 2021
=> libpkgconf-1.8.0-r0: running pre_pkg hook: 098_lint...
=> libpkgconf-1.8.0-r0: running pre_pkg hook: 099_scriptlets...
=> libpkgconf-1.8.0-r0: running pre_pkg hook: 999_collected_rdeps...
=> pkgconf-devel-1.8.0-r0: running pre_pkg hook: 001_runtime_deps...
   symlink: usr/lib/libpkgconf.so.3.0.0 <-> libpkgconf
=> pkgconf-devel-1.8.0-r0: running pre_pkg hook: 002_cmd_provides...
=> pkgconf-devel-1.8.0-r0: running pre_pkg hook: 003_pc_provides...
=> pkgconf-devel-1.8.0-r0: ERROR: failed scanning .pc files (missing pkgconf?)
Traceback (most recent call last):
  File "/cports/src/runner.py", line 909, in fire
    case "bootstrap": bootstrap(cmd)
  File "/cports/src/runner.py", line 391, in bootstrap
    do_pkg("pkg", "main/base-cbuild", False, False, stage = 1)
  File "/cports/src/runner.py", line 858, in do_pkg
    build.build(
  File "/cports/src/cbuild/core/build.py", line 53, in build
    dependencies.install(
  File "/cports/src/cbuild/core/dependencies.py", line 441, in install
    build.build(step, template.read_pkg(
  File "/cports/src/cbuild/core/build.py", line 53, in build
    dependencies.install(
  File "/cports/src/cbuild/core/dependencies.py", line 428, in install
    build.build(step, template.read_pkg(
  File "/cports/src/cbuild/core/build.py", line 53, in build
    dependencies.install(
  File "/cports/src/cbuild/core/dependencies.py", line 415, in install
    build.build(step, template.read_pkg(
  File "/cports/src/cbuild/core/build.py", line 107, in build
    prepkg.invoke(sp)
  File "/cports/src/cbuild/step/prepkg.py", line 11, in invoke
    template.call_pkg_hooks(pkg, "pre_pkg")
  File "/cports/src/cbuild/core/template.py", line 165, in call_pkg_hooks
    run_pkg_func(pkg, f[0], f"{stepn}_{f[1]}", f"{stepn} hook: {f[1]}")
  File "/cports/src/cbuild/core/template.py", line 160, in run_pkg_func
    func(pkg)
  File "/cports/src/cbuild/hooks/pre_pkg/003_pc_provides.py", line 65, in invoke
    scan_pc(f)
  File "/cports/src/cbuild/hooks/pre_pkg/003_pc_provides.py", line 46, in scan_pc
    pkg.error("failed scanning .pc files (missing pkgconf?)")
  File "/cports/src/cbuild/core/template.py", line 183, in error
    raise errors.PackageException(msg, end, self)
cbuild.core.errors.PackageException: failed scanning .pc files (missing pkgconf?)
Bootstrap failed!
```
for some reason, option "`!scanpkgconf`" is not propagated ?

**Comment by q66** [comment]
it should not be propagated
