### ISSUE TITLE
main/byacc fails building on bootstrap stage 1

### ISSUE THREAD

**Issue by yopito** [chimera-linux/cports#99]
context: bootstrap on x86_64 using rev d77e1e53

It was fine on building byacc on april (my previous bootstrap).

```
$ PYTHONUNBUFFERED=1 BOOTSTRAP_ROOT=/build/chimera/SCRATCH_cports.git/bootstrap.ROOTDIR ./bootstrap.sh
...
=> cbuild: bootstrapping stage 1
=> cbuild: removing autodeps...
=> base-cbuild-0.1-r0: building [meta] for x86_64...
   [runtime] musl-devel>=0: not found
   [runtime] elftoolchain>=0: not found
   [runtime] llvm>=0: not found
   [runtime] clang>=0: not found
   [runtime] lld>=0: not found
...
=> elftoolchain-0.7.1_svn20220506-r0: building [makefile] (dependency of base-cbuild) for x86_64...
   [host] bsdm4: not found
   [host] byacc: not found
   [host] flex: not found
   [target] libarchive-devel: not found
   [target] musl-bsd-headers: not found
   [runtime] libelf=0.7.1_svn20220506-r0: subpackage (ignored)
=> cbuild: removing autodeps...
=> bsdm4-0.99.1-r0: building [makefile] (dependency of elftoolchain) for x86_64...
   [host] byacc: not found
=> cbuild: removing autodeps...
=> byacc-20220128-r0: building [gnu_configure] (dependency of bsdm4) for x86_64...
=> byacc-20220128-r0: running do_fetch hook: 000_sources...
=> byacc-20220128-r0: running do_extract hook: 000_sources...
=> byacc-20220128-r0: running init_patch hook: 000_env_pkg_config...
=> byacc-20220128-r0: running do_patch hook: 000_patches...
=> byacc-20220128-r0: running pre_configure hook: 000_script_wrapper...
=> byacc-20220128-r0: running pre_configure hook: 001_prepare_users...
=> byacc-20220128-r0: running do_configure...
checking build system type... x86_64-chimera-linux-musl
checking host system type... x86_64-chimera-linux-musl
checking target system type... x86_64-chimera-linux-musl
Configuring for linux-musl
checking for x86_64-chimera-linux-musl-gcc... clang
checking for C compiler default output... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for executable suffix... 
checking for object suffix... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking version of clang... 14.0.1
checking if this is really Intel C compiler... no
checking if this is really Clang C compiler... yes
checking version of clang... 14.0.1
checking if option -Qunused-arguments works... yes
checking if option -Wno-error=implicit-function-declaration works... yes
checking for clang option to accept ANSI C... none needed
checking $CFLAGS variable... broken
configure: WARNING: your environment uses the CFLAGS variable to hold CPPFLAGS options
checking $CC variable... ok
checking whether bmake sets ${MAKE}... yes
checking for a BSD compatible install... /usr/bin/install -c
checking if filesystem supports mixed-case filenames... yes
checking for exctags... no
checking for ctags... no
checking for exetags... no
checking for etags... no
checking for ctags... no
checking for etags... no
checking for mawk... no
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking for lint... no
checking for cppcheck... no
checking for splint... no
checking if the POSIX test-macros are already defined... no
checking if this is the GNU C library... no
checking if _XOPEN_SOURCE really is set... yes
checking for ggrep... no
checking for grep... grep
checking for egrep... grep -E
checking how to run the C preprocessor... clang-cpp
checking for fcntl.h... yes
checking for unistd.h... yes
checking for working mkstemp... yes
checking for unistd.h... (cached) yes
checking for getopt.h... yes
checking for header declaring getopt variables... unistd.h
checking for getopt... yes
checking for vsnprintf... yes
checking for maximum table size... default
checking if backtracking extension is wanted... 
checking for fgrep... grep -F
checking if you want to use C11 _Noreturn feature... no
checking if you want to turn on gcc warnings... no
configure: checking for clang __attribute__ directives...
... scanf
... printf
... unused
... noreturn
checking if you want to see long compiling messages... yes
checking if you want to use dmalloc for testing... no
checking if you want to use dbmalloc for testing... no
checking if you want to use valgrind for testing... no
checking if you want to perform memory-leak testing... no
checking for groff... no
checking for nroff... no
checking for mandoc... no
checking for tbl... cat
checking for man2html... no
checking for program to convert manpage to html... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... (cached) yes
checking for mode_t... yes
configure: creating ./config.status
config.status: creating makefile
cp: /tmp/csABGiEA/out: Cross-device link
config.status: creating config.h
=> byacc-20220128-r0: running do_build...
bmake: bmake: don't know how to make yacc.1. Stop

bmake: stopped in /builddir/byacc-20220128/build
=> A failure has occurred!
Traceback (most recent call last):
  File "/cports/src/runner.py", line 1202, in fire
    case "bootstrap": bootstrap(cmd)
  File "/cports/src/runner.py", line 429, in bootstrap
    do_pkg("pkg", "main/base-cbuild", False, False, stage = 1)
  File "/cports/src/runner.py", line 930, in do_pkg
    build.build(
  File "/cports/src/cbuild/core/build.py", line 57, in build
    if dependencies.install(
  File "/cports/src/cbuild/core/dependencies.py", line 418, in install
    build.build(
  File "/cports/src/cbuild/core/build.py", line 57, in build
    if dependencies.install(
  File "/cports/src/cbuild/core/dependencies.py", line 381, in install
    build.build(
  File "/cports/src/cbuild/core/build.py", line 57, in build
    if dependencies.install(
  File "/cports/src/cbuild/core/dependencies.py", line 381, in install
    build.build(
  File "/cports/src/cbuild/core/build.py", line 100, in build
    buildm.invoke(pkg, step)
  File "/cports/src/cbuild/step/build.py", line 14, in invoke
    pkg.run_step("build", optional = True)
  File "/cports/src/cbuild/core/template.py", line 1068, in run_step
    if not run_pkg_func(self, "do_" + stepn) and not optional:
  File "/cports/src/cbuild/core/template.py", line 164, in run_pkg_func
    func(pkg)
  File "/cports/src/cbuild/build_style/gnu_configure.py", line 8, in do_build
    self.make.build()
  File "/cports/src/cbuild/util/make.py", line 80, in build
    return self._invoke(
  File "/cports/src/cbuild/util/make.py", line 63, in _invoke
    return self.template.do(
  File "/cports/src/cbuild/core/template.py", line 1046, in do
    return chroot.enter(
  File "/cports/src/cbuild/core/chroot.py", line 437, in enter
    return subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bwrap', '--unshare-all', '--hostname', 'cbuild', '--ro-bind', PosixPath('/cports/bldroot-stage0'), '/', '--bind', PosixPath('/cports/bldroot-stage0/builddir'), '/builddir', '--ro-bind', PosixPath('/cports/bldroot-stage0/destdir'), '/destdir', '--ro-bind', PosixPath('/cports/sources'), '/sources', '--dev', '/dev', '--proc', '/proc', '--tmpfs', '/tmp', '--tmpfs', '/var/tmp', '--new-session', '--die-with-parent', '--bind', PosixPath('/cports/cbuild_cache'), '/cbuild_cache', '--uid', '1337', '--gid', '1337', '--chdir', PosixPath('/builddir/byacc-20220128/build'), 'bmake', '-j3']' returned non-zero exit status 2.
Bootstrap failed!
```

**Comment by yopito** [comment]
file exists but not found ?
```
$ file bldroot-stage0/builddir/byacc-20220128/yacc.1
bldroot-stage0/builddir/byacc-20220128/yacc.1: troff or preprocessor input, ASCII text
```

**Comment by yopito** [comment]
using "`make_dir = "."`" in byacc/template.py : find yacc.1 file but fails:
```
=> byacc-20220128-r0: running do_build...
--- yacc.txt ---
/bin/sh -c "tbl yacc.1 | nroff -man | col -bx" >yacc.txt
/bin/sh: 1: tbl: not found
/bin/sh: 1: nroff: not found
```
why `yacc.txt` is requested on build ?

**Comment by yopito** [comment]
in fact, configure seems to generate makefile from itself, instead of using `makefile.in` ?

**Comment by q66** [comment]
works for me, you'll have to figure it out

**Comment by yopito** [comment]
thanks for your check. really weird, let's dig into.

**Comment by q66** [comment]
i'd start by tracking down the cross-device link configure message

**Comment by yopito** [comment]
for the record, some inputs ..

this is really crazy:
* stage0 was performed successfully, then gmake has been packaged on stage1, so with numerous copy of files.
* build is carefully managed via cbuild, bubblewrap & co, so why do I have such a specific problem ?

I've straced the full process, the copy stuff is this part:
```
[pid  9124] rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
[pid  9124] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9fc08b7000
[pid  9124] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9fc08b6000
[pid  9124] execve("/usr/bin/cp", ["cp", "/tmp/csjkEhJp/out", "makefile"], 0x7f9fc08b7088 /* 213 vars */ <unfinished ...>
[pid  9124] <... execve resumed>)       = 0
[pid  9124] arch_prctl(ARCH_SET_FS, 0x7f4a5f4493d8) = 0
[pid  9124] set_tid_address(0x7f4a5f446e18) = 945
[pid  9124] brk(NULL)                   = 0x560686b1f000
[pid  9124] brk(0x560686b21000)         = 0x560686b21000
[pid  9124] mmap(0x560686b1f000, 4096, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x560686b1f000
[pid  9124] open("/etc/ld-musl-x86_64.path", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  9124] open("/lib/libfts.so.0", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
[pid  9124] fcntl(3, F_SETFD, FD_CLOEXEC) = 0
[pid  9124] fstat(3, {st_mode=S_IFREG|0755, st_size=13000, ...}) = 0
[pid  9124] read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\360\35\0\0\0\0\0\0"..., 960) = 960
[pid  9124] mmap(NULL, 24576, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f4a5f386000
[pid  9124] mmap(0x7f4a5f387000, 12288, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x7f4a5f387000
[pid  9124] mmap(0x7f4a5f38a000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x2000) = 0x7f4a5f38a000
[pid  9124] mmap(0x7f4a5f38b000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x2000) = 0x7f4a5f38b000
[pid  9124] close(3)                    = 0
[pid  9124] mprotect(0x7f4a5f38a000, 4096, PROT_READ) = 0
[pid  9124] mprotect(0x7f4a5f445000, 4096, PROT_READ) = 0
[pid  9124] mprotect(0x560686ac5000, 4096, PROT_READ) = 0
[pid  9124] rt_sigprocmask(SIG_UNBLOCK, [RT_1 RT_2], NULL, 8) = 0
[pid  9124] rt_sigaction(SIGUSR1, {sa_handler=0x560686ac2ed0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f4a5f422ba9}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
[pid  9124] stat("makefile", 0x7ffc40b59600) = -1 ENOENT (No such file or directory)
[pid  9124] lstat("/tmp/csjkEhJp/out", {st_mode=S_IFREG|0644, st_size=3529, ...}) = 0
[pid  9124] umask(0777)                 = 022
[pid  9124] umask(022)                  = 0777
[pid  9124] mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f4a5f382000
[pid  9124] stat("/tmp/csjkEhJp/out", {st_mode=S_IFREG|0644, st_size=3529, ...}) = 0
[pid  9124] stat("makefile", 0x7ffc40b59510) = -1 ENOENT (No such file or directory)
[pid  9124] open("/tmp/csjkEhJp/out", O_RDONLY|O_LARGEFILE) = 3
[pid  9124] open("makefile", O_WRONLY|O_CREAT|O_TRUNC|O_LARGEFILE, 0100644) = 4
[pid  9124] sysinfo({uptime=62603, loads=[106432, 50912, 37152], totalram=8219549696, freeram=3065122816, sharedram=111833088, bufferram=176664576, totalswap=8698982400, freeswap=8698982400, procs=680, totalhigh=0, freehigh=0, mem_unit=1}) = 0
[pid  9124] mmap(NULL, 2097172, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f4a5f181000
[pid  9124] copy_file_range(3, NULL, 4, NULL, 9223372036854775807, 0) = -1 EXDEV (Cross-device link)
[pid  9124] writev(2, [{iov_base="cp: ", iov_len=4}, {iov_base=NULL, iov_len=0}], 2) = 4
[pid  9124] writev(2, [{iov_base="/tmp/csjkEhJp/out", iov_len=17}, {iov_base=NULL, iov_len=0}], 2 <unfinished ...>
[pid  9124] <... writev resumed>)       = 17
[pid  9124] writev(2, [{iov_base="", iov_len=0}, {iov_base=": ", iov_len=2}], 2 <unfinished ...>
[pid  9124] <... writev resumed>)       = 2
[pid  9124] writev(2, [{iov_base="", iov_len=0}, {iov_base="Cross-device link", iov_len=17}], 2 <unfinished ...>
[pid  9124] <... writev resumed>)       = 17
[pid  9124] writev(2, [{iov_base="", iov_len=0}, {iov_base="\n", iov_len=1}], 2 <unfinished ...>
[pid  9124] <... writev resumed>)       = 1
[pid  9124] close(4 <unfinished ...>
[pid  9124] <... close resumed>)        = 0
[pid  9124] close(3 <unfinished ...>
[pid  9124] <... close resumed>)        = 0
[pid  9124] munmap(0x7f4a5f382000, 16384 <unfinished ...>
[pid  9124] <... munmap resumed>)       = 0
[pid  9124] exit_group(1 <unfinished ...>
[pid  9124] <... exit_group resumed>)   = ?
[pid  9124] +++ exited with 1 +++
```

According to https://man7.org/linux/man-pages/man2/copy_file_range.2.html, `copy_file_range` syscall is designed for file copy via kernel, and support crossFS copy with kernel 5.3 . 

So why does it return error `EXDEV` (not same FS) in my context ? my kernel is 5.15.57_1,  using musl libc and through bubblewrap, so it might have some side-effect ?

**Comment by yopito** [comment]
quick and dirty workaround that is fine:
```diff
[SCRATCH_cports.git]$ git diff main/byacc/template.py 
diff --git a/main/byacc/template.py b/main/byacc/template.py
index 54c1f655..9408cdd6 100644
--- a/main/byacc/template.py
+++ b/main/byacc/template.py
@@ -9,6 +9,7 @@ license="custom:byacc"
 url = "http://invisible-island.net/byacc"
 source = f"ftp://ftp.invisible-island.net/{pkgname}/{pkgname}-{pkgver}.tgz"
 sha256 = "42c1805cc529314e6a76326fe1b33e80c70862a44b01474da362e2f7db2d749c"
+env = { "TMPDIR": self.make_dir }
 options = ["bootstrap"]
 
 def post_install(self):
```
so stage1 build go ahead ... and fail few packages later, on ncurses with the same error on copying file crossFS:
```
...
=> ncurses-6.3-r0: building [gnu_configure] (dependency of less) for x86_64...
   [host] pkgconf: found (1.8.0-r0)
   [host] gmake: found (4.3-r0)
   [runtime] ncurses-base=6.3-r0: subpackage (ignored)
   [runtime] ncurses-devel=6.3-r0: subpackage (ignored)
   [runtime] ncurses-base=6.3-r0: subpackage (ignored)
=> ncurses-6.3-r0: installing host dependencies: pkgconf, gmake
=> ncurses-6.3-r0: running do_fetch hook: 000_sources...
=> ncurses-6.3-r0: running do_extract hook: 000_sources...
=> ncurses-6.3-r0: running init_patch hook: 000_env_pkg_config...
=> ncurses-6.3-r0: running do_patch hook: 000_patches...
=> ncurses-6.3-r0: running init_configure...
=> ncurses-6.3-r0: running pre_configure hook: 000_script_wrapper...
=> ncurses-6.3-r0: running pre_configure hook: 001_prepare_users...
=> ncurses-6.3-r0: running do_configure...
....
checking c++ library-dependency suffix... w.a
checking where we will install curses.h... ${prefix}/include
checking for desired basename for form library... form
checking for desired basename for menu library... menu
checking for desired basename for panel library... panel
checking for desired basename for cxx library... ncurses++
checking for src modules... ncurses progs panel menu form
checking for defines to add to ncursesw6-config script... 
package: ncursesw
checking for linker search path... /usr/lib /lib
configure: creating ./config.status
config.status: creating include/MKterm.h.awk
cp: /tmp/csDfLJLm/out: Cross-device link
config.status: creating include/curses.head
cp: /tmp/csDfLJLm/out: Cross-device link
config.status: creating include/ncurses_dll.h
cp: /tmp/csDfLJLm/out: Cross-device link
config.status: creating include/termcap.h
cp: /tmp/csDfLJLm/out: Cross-device link
...
config.status: creating Makefile
cp: /tmp/csDfLJLm/out: Cross-device link
config.status: creating include/ncurses_cfg.h
Appending rules for shared model (ncurses: ticlib+termlib+ext_tinfo+base+widechar+ext_funcs)
Appending rules for normal model (ncurses: ticlib+termlib+ext_tinfo+base+widechar+ext_funcs)
Appending rules for shared model (progs: ticlib+termlib+ext_tinfo+base+widechar+ext_funcs)
Appending rules for normal model (progs: ticlib+termlib+ext_tinfo+base+widechar+ext_funcs)
Appending rules for shared model (panel: ticlib+termlib+ext_tinfo+base+widechar+ext_funcs)
Appending rules for normal model (panel: ticlib+termlib+ext_tinfo+base+widechar+ext_funcs)
Appending rules for shared model (menu: ticlib+termlib+ext_tinfo+base+widechar+ext_funcs)
Appending rules for normal model (menu: ticlib+termlib+ext_tinfo+base+widechar+ext_funcs)
Appending rules for shared model (form: ticlib+termlib+ext_tinfo+base+widechar+ext_funcs)
Appending rules for normal model (form: ticlib+termlib+ext_tinfo+base+widechar+ext_funcs)
Appending rules for shared model (test: ticlib+termlib+ext_tinfo+base+widechar+ext_funcs)
Appending rules for normal model (test: ticlib+termlib+ext_tinfo+base+widechar+ext_funcs)
Appending rules for shared model (c++: ticlib+termlib+ext_tinfo+base+widechar+ext_funcs)
creating headers.sh
Makefile:1: *** recipe commences before first target.  Stop.
=> A failure has occurred!
Traceback (most recent call last):
```

**Comment by q66** [comment]
that is why quick and dirty workarounds are pointless, something is either wrong with your system or there is something else you will need to figure out

**Comment by q66** [comment]
maybe it's https://github.com/torvalds/linux/commit/868f9f2f8e004bfe0d3935b1976f625b2924893b ? it was introduced in 5.15 kernel in 5.15.53

**Comment by q66** [comment]
can you try getting https://github.com/chimera-linux/bsdutils/commit/796f0969cbc8fee0a098f2aeb9ebb67451d8e0df.patch into your `bsdutils` and see if it fixes the problem?

**Comment by yopito** [comment]
yes, it fixes it ! awesome catch, many thanks for your help.
btw, your patch includes changes on both `src/cp/utils.c` and `patches/src/cp/utils.c.patch`. it's expected ?
do you keep this issue opened until bsdutils package incorporate this change ?

**Comment by q66** [comment]
the patches in `patches/` represent the diff over freebsd upstream sources, so they need updating whenever a change is done
